---
- name: Download grafana.deb
  become: true
  become_user: root
  get_url:
    url: https://grafanarel.s3.amazonaws.com/builds/grafana_4.0.0-1478693311beta1_amd64.deb
    dest: /home/ubuntu/grafana_4.0.0-1478693311beta1_amd64.deb
    mode: 0644

- name: install adduser libfontconfig
  become: true
  become_user: root
  apt: name={{item}} state=installed update_cache=true
  with_items:
       - adduser
       - libfontconfig

- name: dpkg grafana.deb
  become: true
  become_user: root
  shell: dpkg -i grafana_4.0.0-1478693311beta1_amd64.deb
 
- name: Restart grafana-server
  become: true
  become_user: root
  service: name=grafana-server state=restarted

- name: Copy shellscript for creating datasource (1)
  template: src=create_datasource.sh.j2 dest=/home/ubuntu/create_datasource.sh

- name: Copy shellscript for creating datasource (2)
  template: src=create_dashboard.sh.j2 dest=/home/ubuntu/create_dashboard.sh

- name: Copy shellscript for creating datasource (3)
  template: src=create_dashboard_api.sh.j2 dest=/home/ubuntu/create_dashboard_api.sh

- name: Copy shellscript for creating datasource (4)
  template: src=create_dashboard_db.sh.j2 dest=/home/ubuntu/create_dashboard_db.sh

- name: Copy shellscript for creating datasource (5)
  template: src=create_dashboard_cache.sh.j2 dest=/home/ubuntu/create_dashboard_cache.sh

- name: Create Influxdb Datasource
  shell: sh create_datasource.sh

- name: Get hostname
  shell: hostname
  register: hostname

- name: Create Dashboard
  shell: sh create_dashboard.sh {{ipAddr}} {{hostname.stdout}} {{serverTag}}
